[package]
name = "social-todo-server"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"

[dependencies]
actix-files = "0.5"
actix-web = "3"
serde_json = "1"
structopt = "0.3"
tracing = "0.1"
tracing-actix-web = "0.2"
tracing-subscriber = "0.2"
