[package]
name = "social-todo-server"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"

[dependencies]
actix-files = "0.5"
actix-web = "3"
env_logger = "0.8"
log = "0.4"
serde_json = "1"
structopt = "0.3"
